# Import Liabraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [93]:
tf.__version__

'2.5.0'

# Import Dataset

In [32]:
dataset = pd.read_csv('C:/Users/User/Downloads/Telco-Customer-Churn.csv')
x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [33]:
print(x)

[['Female' 0 'Yes' ... 'Electronic check' 29.85 '29.85']
 ['Male' 0 'No' ... 'Mailed check' 56.95 '1889.5']
 ['Male' 0 'No' ... 'Mailed check' 53.85 '108.15']
 ...
 ['Female' 0 'Yes' ... 'Electronic check' 29.6 '346.45']
 ['Male' 1 'Yes' ... 'Mailed check' 74.4 '306.6']
 ['Male' 0 'No' ... 'Bank transfer (automatic)' 105.65 '6844.5']]


In [34]:
print(y)

['No' 'No' 'Yes' ... 'No' 'Yes' 'No']


# Converting TotalCharges column from string to Integer

In [35]:
#this will show the wheather the values in the total chargers are null or not
#pd will convert the string datatype to numeric
pd.to_numeric(dataset.TotalCharges, errors='coerce').isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
7038    False
7039    False
7040    False
7041    False
7042    False
Name: TotalCharges, Length: 7043, dtype: bool

In [36]:
#this will show the dataset with null values in the TotalCharges column
dataset[pd.to_numeric(dataset.TotalCharges, errors='coerce').isnull()] 

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
488   4472-LVYGI  Female              0     Yes        Yes       0   
753   3115-CZMZD    Male              0      No        Yes       0   
936   5709-LVOEQ  Female              0     Yes        Yes       0   
1082  4367-NUYAO    Male              0     Yes        Yes       0   
1340  1371-DWPAZ  Female              0     Yes        Yes       0   
3331  7644-OMVMY    Male              0     Yes        Yes       0   
3826  3213-VVOLG    Male              0     Yes        Yes       0   
4380  2520-SGTTA  Female              0     Yes        Yes       0   
5218  2923-ARZLG    Male              0     Yes        Yes       0   
6670  4075-WKNIU  Female              0     Yes        Yes       0   
6754  2775-SEFEE    Male              0      No        Yes       0   

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
488            No  No phone service             DSL                  Yes  ...   
753           Yes                No              No  No internet service  ...   
936           Yes                No             DSL                  Yes  ...   
1082          Yes               Yes              No  No internet service  ...   
1340           No  No phone service             DSL                  Yes  ...   
3331          Yes                No              No  No internet service  ...   
3826          Yes               Yes              No  No internet service  ...   
4380          Yes                No              No  No internet service  ...   
5218          Yes                No              No  No internet service  ...   
6670          Yes               Yes             DSL                   No  ...   
6754          Yes               Yes             DSL                  Yes  ...   

         DeviceProtection          TechSupport          StreamingTV  \
488                   Yes                  Yes                  Yes   
753   No internet service  No internet service  No internet service   
936                   Yes                   No                  Yes   
1082  No internet service  No internet service  No internet service   
1340                  Yes                  Yes                  Yes   
3331  No internet service  No internet service  No internet service   
3826  No internet service  No internet service  No internet service   
4380  No internet service  No internet service  No internet service   
5218  No internet service  No internet service  No internet service   
6670                  Yes                  Yes                  Yes   
6754                   No                  Yes                   No   

          StreamingMovies  Contract PaperlessBilling  \
488                    No  Two year              Yes   
753   No internet service  Two year               No   
936                   Yes  Two year               No   
1082  No internet service  Two year               No   
1340                   No  Two year               No   
3331  No internet service  Two year               No   
3826  No internet service  Two year               No   
4380  No internet service  Two year               No   
5218  No internet service  One year              Yes   
6670                   No  Two year               No   
6754                   No  Two year              Yes   

                  PaymentMethod MonthlyCharges  TotalCharges Churn  
488   Bank transfer (automatic)          52.55                  No  
753                Mailed check          20.25                  No  
936                Mailed check          80.85                  No  
1082               Mailed check          25.75                  No  
1340    Credit card (automatic)          56.05                  No  
3331               Mailed check          19.85                  No  
3826               Mailed check          25.35                  No  
4380               Mailed check          20.00                  No  
5218               Mailed check          19.7

## Taking care of missing values

In [37]:
 #There were only 11 rows with value null in it for TotalCharges, so we dropped those 11 rows fromm total of 7043 rows
dataset1= dataset[dataset.TotalCharges!=' ']
dataset1.shape

(7032, 21)

In [38]:
#Now theere is new dataset1 without any null values
dataset1.TotalCharges= pd.to_numeric(dataset1.TotalCharges)

C:\Users\User\anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [39]:
dataset1.TotalCharges.dtypes

dtype('float64')

In [41]:
#storing new dataset1 values in x1 and y1
x1 = dataset1.iloc[:, 1:-1].values
y1 = dataset1.iloc[:, -1].values

In [42]:
print(x1)

[['Female' 0 'Yes' ... 'Electronic check' 29.85 29.85]
 ['Male' 0 'No' ... 'Mailed check' 56.95 1889.5]
 ['Male' 0 'No' ... 'Mailed check' 53.85 108.15]
 ...
 ['Female' 0 'Yes' ... 'Electronic check' 29.6 346.45]
 ['Male' 1 'Yes' ... 'Mailed check' 74.4 306.6]
 ['Male' 0 'No' ... 'Bank transfer (automatic)' 105.65 6844.5]]


# Encoding the Categorical data

## Encoding Independent Variable

In [43]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,2,3,5,6,7,8,9,10,11,12,13,14,15,16])], remainder= 'passthrough')
x1 = np.array(ct.fit_transform(x1)) 

In [46]:
print(x1)

[[1.0 0.0 0.0 ... 1 29.85 29.85]
 [0.0 1.0 1.0 ... 34 56.95 1889.5]
 [0.0 1.0 1.0 ... 2 53.85 108.15]
 ...
 [1.0 0.0 0.0 ... 11 29.6 346.45]
 [0.0 1.0 0.0 ... 4 74.4 306.6]
 [0.0 1.0 1.0 ... 66 105.65 6844.5]]


## Encoding Dependent variable

In [50]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y1 = le.fit_transform(y1) 

In [51]:
print(y1)

[0 0 1 ... 0 1 0]


# Splitting dataset1 into training set and test set

In [83]:
from sklearn.model_selection import train_test_split
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size = 0.25, random_state = 1 )

In [84]:
print(x1_train)

[[1.0 0.0 0.0 ... 71 105.15 7555.0]
 [1.0 0.0 1.0 ... 49 19.45 921.3]
 [0.0 1.0 1.0 ... 72 19.3 1414.8]
 ...
 [1.0 0.0 1.0 ... 11 76.5 837.95]
 [0.0 1.0 1.0 ... 2 54.4 114.1]
 [0.0 1.0 1.0 ... 1 69.65 69.65]]


In [88]:
print(y1_train)

[0 0 0 ... 1 1 1]


# Feature scaling 

In [89]:
# making numerical values b/w -3 to +3
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x1_train = sc.fit_transform(x1_train)
x1_test = sc.transform(x1_test)

In [90]:
print(x1_train)

[[ 1.00952584 -1.00952584 -1.03866899 ...  1.57743883  1.33038512
   2.30352715]
 [ 1.00952584 -1.00952584  0.96277063 ...  0.68114359 -1.51085447
  -0.60110389]
 [-0.99056405  0.99056405  0.96277063 ...  1.61817952 -1.51582747
  -0.38502005]
 ...
 [ 1.00952584 -1.00952584  0.96277063 ... -0.86700272  0.38054248
  -0.63759951]
 [-0.99056405  0.99056405  0.96277063 ... -1.23366896 -0.35214591
  -0.95454438]
 [-0.99056405  0.99056405  0.96277063 ... -1.27440965  0.15344223
  -0.97400726]]


In [91]:
print(x1_test)

[[-0.99056405  0.99056405 -1.03866899 ...  1.61817952 -1.33514187
  -0.1904789 ]
 [ 1.00952584 -1.00952584 -1.03866899 ... -0.66329926  0.67394937
  -0.40238119]
 [ 1.00952584 -1.00952584  0.96277063 ...  1.25151329  1.07510455
   1.7334336 ]
 ...
 [ 1.00952584 -1.00952584  0.96277063 ...  1.21077259  0.96072559
   1.51634267]
 [ 1.00952584 -1.00952584 -1.03866899 ... -0.13367026 -1.29038489
  -0.70126434]
 [ 1.00952584 -1.00952584 -1.03866899 ...  0.84410636  1.29391646
   1.43279901]]


# Building ANN

In [94]:
#Step 1: Initializing the ANN
ann = tf.keras.models.Sequential()


In [95]:
#step 2: Adding the input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [96]:
#step 3: Adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [97]:
#step 4: Adding the Output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN

In [98]:
#Compiling the ANN
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

In [125]:
#Training the ANN on Training set
ann.fit(x1_train, y1_train, batch_size = 64, epochs= 100)

Epoch 1/100
83/83 [==============================] - 0s 2ms/step - loss: 0.3845 - accuracy: 0.8165
Epoch 2/100
83/83 [==============================] - 0s 3ms/step - loss: 0.3838 - accuracy: 0.8168
Epoch 3/100
83/83 [==============================] - 0s 2ms/step - loss: 0.3838 - accuracy: 0.8174
Epoch 4/100
83/83 [==============================] - 0s 2ms/step - loss: 0.3835 - accuracy: 0.8168
Epoch 5/100
83/83 [==============================] - 0s 3ms/step - loss: 0.3836 - accuracy: 0.8159
Epoch 6/100
83/83 [==============================] - 0s 3ms/step - loss: 0.3836 - accuracy: 0.8166
Epoch 7/100
83/83 [==============================] - 0s 3ms/step - loss: 0.3832 - accuracy: 0.8166
Epoch 8/100
83/83 [==============================] - 0s 3ms/step - loss: 0.3833 - accuracy: 0.8161
Epoch 9/100
83/83 [==============================] - 0s 3ms/step - loss: 0.3830 - accuracy: 0.8182
Epoch 10/100
83/83 [==============================] - 0s 2ms/step - loss: 0.3834 - accuracy: 0.8166
Epoch 11/

# Predicting the test set result

In [126]:
y1_pred = ann.predict(x1_test)
y1_pred = (y1_pred > 0.5)
print(np.concatenate((y1_pred.reshape(len(y1_pred),1), y1_test.reshape(len(y1_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Making confusion Matrix

In [127]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y1_test, y1_pred)
print(cm)
accuracy_score(y1_test, y_pred)

[[1149  145]
 [ 215  249]]


0.7952218430034129